import type { WeaponCategory, WeaponTierInfo } from "~/models/weaponMastery";

export const WEAPON_NAMES: Record<string, string> = {
  Item_Weapon_ACE32_C: "ACE32",
  Item_Weapon_AK47_C: "AKM",
  Item_Weapon_AUG_C: "AUG A3",
  Item_Weapon_AWM_C: "AWM",
  Item_Weapon_Berreta686_C: "S686",
  Item_Weapon_BerylM762_C: "Beryl M762",
  Item_Weapon_BizonPP19_C: "PP-19 Bizon",
  Item_Weapon_Crossbow_C: "Crossbow",
  Item_Weapon_DP12_C: "DBS",
  Item_Weapon_DP28_C: "DP-28",
  Item_Weapon_Dragunov_C: "Dragunov",
  Item_Weapon_FAMASG2_C: "FAMAS",
  Item_Weapon_FNFal_C: "SLR",
  Item_Weapon_G18_C: "P18C",
  Item_Weapon_G36C_C: "G36C",
  Item_Weapon_Groza_C: "Groza",
  Item_Weapon_HK416_C: "M416",
  Item_Weapon_K2_C: "K2",
  Item_Weapon_Kar98k_C: "Kar98k",
  Item_Weapon_M16A4_C: "M16A4",
  Item_Weapon_M1911_C: "P1911",
  Item_Weapon_M249_C: "M249",
  Item_Weapon_M24_C: "M24",
  Item_Weapon_M9_C: "P92",
  Item_Weapon_MG3_C: "MG3",
  Item_Weapon_MP5K_C: "MP5K",
  Item_Weapon_MP9_C: "MP9",
  Item_Weapon_Mini14_C: "Mini14",
  Item_Weapon_Mk12_C: "Mk12",
  Item_Weapon_Mk14_C: "Mk14",
  Item_Weapon_Mk47Mutant_C: "Mk47 Mutant",
  Item_Weapon_Mosin_C: "Mosin-Nagant",
  Item_Weapon_NagantM1895_C: "R1895",
  Item_Weapon_P90_C: "P90",
  Item_Weapon_QBU88_C: "QBU",
  Item_Weapon_QBZ95_C: "QBZ95",
  Item_Weapon_SCAR_L_C: "SCAR-L",
  "Item_Weapon_SCAR-L_C": "SCAR-L",
  Item_Weapon_SKS_C: "SKS",
  Item_Weapon_Thompson_C: "Tommy Gun",
  Item_Weapon_UMP_C: "UMP45",
  Item_Weapon_UZI_C: "Micro UZI",
  Item_Weapon_VSS_C: "VSS",
  Item_Weapon_Vector_C: "Vector",
  Item_Weapon_Win1894_C: "Win94",
  Item_Weapon_Winchester_C: "S1897",
  Item_Weapon_vz61Skorpion_C: "Skorpion",
  Item_Weapon_JS9_C: "JS9",
  Item_Weapon_L6_C: "Lynx AMR",
  Item_Weapon_OriginS12_C: "O12",
  Item_Weapon_Saiga12_C: "S12K",
  Item_Weapon_Sawnoff_C: "Sawed-off",
  Item_Weapon_DesertEagle_C: "Deagle",
  Item_Weapon_Rhino_C: "Rhino",
  Item_Weapon_PanzerFaust100M_C: "Panzerfaust",
  Item_Weapon_Mortar_C: "Mortar",
  Item_Weapon_Molotov_C: "Molotov",
  Item_Weapon_Grenade_C: "Grenade",
  Item_Weapon_BluezoneGrenade_C: "Bluezone Grenade",
};

export const WEAPON_CATEGORIES: Record<WeaponCategory, string[]> = {
  AR: [
    "Item_Weapon_ACE32_C",
    "Item_Weapon_AK47_C",
    "Item_Weapon_AUG_C",
    "Item_Weapon_BerylM762_C",
    "Item_Weapon_FAMASG2_C",
    "Item_Weapon_G36C_C",
    "Item_Weapon_Groza_C",
    "Item_Weapon_HK416_C",
    "Item_Weapon_K2_C",
    "Item_Weapon_M16A4_C",
    "Item_Weapon_QBZ95_C",
    "Item_Weapon_SCAR_L_C",
    "Item_Weapon_SCAR-L_C",
  ],
  DMR: [
    "Item_Weapon_Dragunov_C",
    "Item_Weapon_FNFal_C",
    "Item_Weapon_Mk14_C",
    "Item_Weapon_Mk47Mutant_C",
    "Item_Weapon_Mini14_C",
    "Item_Weapon_Mk12_C",
    "Item_Weapon_QBU88_C",
    "Item_Weapon_SKS_C",
    "Item_Weapon_VSS_C",
  ],
  SR: [
    "Item_Weapon_AWM_C",
    "Item_Weapon_Kar98k_C",
    "Item_Weapon_M24_C",
    "Item_Weapon_Mosin_C",
    "Item_Weapon_Win1894_C",
    "Item_Weapon_L6_C",
  ],
  SMG: [
    "Item_Weapon_BizonPP19_C",
    "Item_Weapon_MP5K_C",
    "Item_Weapon_MP9_C",
    "Item_Weapon_P90_C",
    "Item_Weapon_Thompson_C",
    "Item_Weapon_UMP_C",
    "Item_Weapon_UZI_C",
    "Item_Weapon_Vector_C",
    "Item_Weapon_vz61Skorpion_C",
    "Item_Weapon_JS9_C",
  ],
  LMG: [
    "Item_Weapon_DP28_C",
    "Item_Weapon_M249_C",
    "Item_Weapon_MG3_C",
  ],
  SG: [
    "Item_Weapon_Berreta686_C",
    "Item_Weapon_DP12_C",
    "Item_Weapon_OriginS12_C",
    "Item_Weapon_Saiga12_C",
    "Item_Weapon_Sawnoff_C",
    "Item_Weapon_Winchester_C",
  ],
  PISTOL: [
    "Item_Weapon_G18_C",
    "Item_Weapon_M1911_C",
    "Item_Weapon_M9_C",
    "Item_Weapon_NagantM1895_C",
    "Item_Weapon_DesertEagle_C",
    "Item_Weapon_Rhino_C",
  ],
  SPECIAL: [
    "Item_Weapon_Crossbow_C",
    "Item_Weapon_Grenade_C",
    "Item_Weapon_Molotov_C",
    "Item_Weapon_BluezoneGrenade_C",
    "Item_Weapon_Mortar_C",
    "Item_Weapon_PanzerFaust100M_C",
  ],
};

export const WEAPON_CATEGORY_LABELS: Record<WeaponCategory | "ALL", string> = {
  ALL: "전체",
  AR: "돌격소총",
  DMR: "지정사수",
  SR: "저격소총",
  SMG: "기관단총",
  LMG: "경기관총",
  SG: "산탄총",
  PISTOL: "권총",
  SPECIAL: "특수",
};

export const TIER_INFO: Record<number, WeaponTierInfo> = {
  0: {
    label: "없음",
    color: "text-gray-500",
    bg: "bg-gray-100 dark:bg-gray-700",
    border: "border-gray-300 dark:border-gray-600",
  },
  1: {
    label: "브론즈",
    color: "text-amber-700",
    bg: "bg-amber-50 dark:bg-amber-900/20",
    border: "border-amber-400",
  },
  2: {
    label: "실버",
    color: "text-slate-500",
    bg: "bg-slate-50 dark:bg-slate-800/50",
    border: "border-slate-400",
  },
  3: {
    label: "골드",
    color: "text-yellow-500",
    bg: "bg-yellow-50 dark:bg-yellow-900/20",
    border: "border-yellow-400",
  },
  4: {
    label: "플래티넘",
    color: "text-cyan-500",
    bg: "bg-cyan-50 dark:bg-cyan-900/20",
    border: "border-cyan-400",
  },
  5: {
    label: "다이아",
    color: "text-blue-500",
    bg: "bg-blue-50 dark:bg-blue-900/20",
    border: "border-blue-500",
  },
  6: {
    label: "마스터",
    color: "text-purple-500",
    bg: "bg-purple-50 dark:bg-purple-900/20",
    border: "border-purple-500",
  },
};

export const TIER_BAR_COLORS = [
  "bg-gray-400",
  "bg-amber-500",
  "bg-slate-400",
  "bg-yellow-400",
  "bg-cyan-400",
  "bg-blue-500",
  "bg-purple-500",
];

export const TIER_DOT_COLORS = [
  "",
  "#b45309",
  "#94a3b8",
  "#eab308",
  "#22d3ee",
  "#3b82f6",
  "#a855f7",
];
