import type { WeaponMasterySummaryResponse } from "~/models/weaponMastery";

export const DUMMY_MASTERY_DATA: WeaponMasterySummaryResponse = {
  data: {
    type: "weaponMasterySummary",
    id: "account.12ddde2e5fec4688ad5a3b10abfe8d59",
    attributes: {
      weaponSummaries: {
        Item_Weapon_ACE32_C: {
          XPTotal: 789219,
          LevelCurrent: 88,
          TierCurrent: 0,
          StatsTotal: { Kills: 43, DamagePlayer: 5048.55, HeadShots: 31, Groggies: 34, MostKillsInAGame: 4 },
        },
        Item_Weapon_AK47_C: {
          XPTotal: 433000,
          LevelCurrent: 60,
          TierCurrent: 0,
          StatsTotal: { Kills: 91, DamagePlayer: 13794.13, HeadShots: 43, Groggies: 65, MostKillsInAGame: 4 },
        },
        Item_Weapon_AUG_C: {
          XPTotal: 224445,
          LevelCurrent: 39,
          TierCurrent: 2,
          StatsTotal: { Kills: 24, DamagePlayer: 3251.99, HeadShots: 8, Groggies: 20, MostKillsInAGame: 5 },
        },
        Item_Weapon_AWM_C: {
          XPTotal: 22654,
          LevelCurrent: 10,
          TierCurrent: 0,
          StatsTotal: { Kills: 1, DamagePlayer: 510.51, HeadShots: 1, Groggies: 2, MostKillsInAGame: 1 },
        },
        Item_Weapon_Berreta686_C: {
          XPTotal: 40461,
          LevelCurrent: 13,
          TierCurrent: 0,
          StatsTotal: { Kills: 5, DamagePlayer: 764.04, HeadShots: 4, Groggies: 4, MostKillsInAGame: 1 },
        },
        Item_Weapon_BerylM762_C: {
          XPTotal: 286475,
          LevelCurrent: 45,
          TierCurrent: 3,
          StatsTotal: { Kills: 443, DamagePlayer: 67759.63, HeadShots: 328, Groggies: 371, MostKillsInAGame: 5 },
        },
        Item_Weapon_BizonPP19_C: {
          XPTotal: 50356,
          LevelCurrent: 15,
          TierCurrent: 0,
          StatsTotal: { Kills: 8, DamagePlayer: 1102.57, HeadShots: 4, Groggies: 8, MostKillsInAGame: 4 },
        },
        Item_Weapon_Crossbow_C: {
          XPTotal: 1555,
          LevelCurrent: 1,
          TierCurrent: 0,
          StatsTotal: { Kills: 0, DamagePlayer: 62.53, HeadShots: 0, Groggies: 0, MostKillsInAGame: 0 },
        },
        Item_Weapon_DP12_C: {
          XPTotal: 71258,
          LevelCurrent: 19,
          TierCurrent: 0,
          StatsTotal: { Kills: 23, DamagePlayer: 2436.94, HeadShots: 3, Groggies: 15, MostKillsInAGame: 5 },
        },
        Item_Weapon_DP28_C: {
          XPTotal: 30306,
          LevelCurrent: 11,
          TierCurrent: 0,
          StatsTotal: { Kills: 7, DamagePlayer: 945.13, HeadShots: 1, Groggies: 6, MostKillsInAGame: 1 },
        },
        Item_Weapon_Dragunov_C: {
          XPTotal: 626528,
          LevelCurrent: 76,
          TierCurrent: 1,
          StatsTotal: { Kills: 0, DamagePlayer: 0, HeadShots: 0, Groggies: 0, MostKillsInAGame: 0 },
        },
        Item_Weapon_FAMASG2_C: {
          XPTotal: 84083,
          LevelCurrent: 21,
          TierCurrent: 0,
          StatsTotal: { Kills: 0, DamagePlayer: 0, HeadShots: 0, Groggies: 0, MostKillsInAGame: 0 },
        },
        Item_Weapon_FNFal_C: {
          XPTotal: 178523,
          LevelCurrent: 33,
          TierCurrent: 3,
          StatsTotal: { Kills: 327, DamagePlayer: 89110.69, HeadShots: 307, Groggies: 343, MostKillsInAGame: 9 },
        },
        Item_Weapon_G18_C: {
          XPTotal: 26930,
          LevelCurrent: 10,
          TierCurrent: 0,
          StatsTotal: { Kills: 4, DamagePlayer: 482.45, HeadShots: 4, Groggies: 1, MostKillsInAGame: 2 },
        },
        Item_Weapon_G36C_C: {
          XPTotal: 51892,
          LevelCurrent: 15,
          TierCurrent: 0,
          StatsTotal: { Kills: 11, DamagePlayer: 1625.94, HeadShots: 7, Groggies: 13, MostKillsInAGame: 4 },
        },
        Item_Weapon_Groza_C: {
          XPTotal: 148738,
          LevelCurrent: 30,
          TierCurrent: 0,
          StatsTotal: { Kills: 17, DamagePlayer: 2401.14, HeadShots: 8, Groggies: 8, MostKillsInAGame: 3 },
        },
        Item_Weapon_HK416_C: {
          XPTotal: 588315,
          LevelCurrent: 73,
          TierCurrent: 2,
          StatsTotal: { Kills: 547, DamagePlayer: 80460.11, HeadShots: 418, Groggies: 508, MostKillsInAGame: 9 },
        },
        Item_Weapon_K2_C: {
          XPTotal: 92191,
          LevelCurrent: 22,
          TierCurrent: 0,
          StatsTotal: { Kills: 8, DamagePlayer: 1380.25, HeadShots: 2, Groggies: 7, MostKillsInAGame: 4 },
        },
        Item_Weapon_Kar98k_C: {
          XPTotal: 340667,
          LevelCurrent: 51,
          TierCurrent: 0,
          StatsTotal: { Kills: 4, DamagePlayer: 1907.80, HeadShots: 5, Groggies: 6, MostKillsInAGame: 1 },
        },
        Item_Weapon_M16A4_C: {
          XPTotal: 383938,
          LevelCurrent: 55,
          TierCurrent: 0,
          StatsTotal: { Kills: 51, DamagePlayer: 10160.56, HeadShots: 26, Groggies: 40, MostKillsInAGame: 3 },
        },
        Item_Weapon_M249_C: {
          XPTotal: 613935,
          LevelCurrent: 75,
          TierCurrent: 0,
          StatsTotal: { Kills: 17, DamagePlayer: 2688.82, HeadShots: 7, Groggies: 12, MostKillsInAGame: 4 },
        },
        Item_Weapon_M24_C: {
          XPTotal: 180982,
          LevelCurrent: 33,
          TierCurrent: 0,
          StatsTotal: { Kills: 10, DamagePlayer: 2166.92, HeadShots: 6, Groggies: 11, MostKillsInAGame: 2 },
        },
        Item_Weapon_MG3_C: {
          XPTotal: 49991,
          LevelCurrent: 15,
          TierCurrent: 0,
          StatsTotal: { Kills: 6, DamagePlayer: 693.75, HeadShots: 1, Groggies: 1, MostKillsInAGame: 2 },
        },
        Item_Weapon_MP5K_C: {
          XPTotal: 323640,
          LevelCurrent: 49,
          TierCurrent: 0,
          StatsTotal: { Kills: 13, DamagePlayer: 1999.59, HeadShots: 4, Groggies: 14, MostKillsInAGame: 5 },
        },
        Item_Weapon_Mini14_C: {
          XPTotal: 937483,
          LevelCurrent: 98,
          TierCurrent: 2,
          StatsTotal: { Kills: 366, DamagePlayer: 95350.14, HeadShots: 401, Groggies: 385, MostKillsInAGame: 7 },
        },
        Item_Weapon_Mk12_C: {
          XPTotal: 952500,
          LevelCurrent: 99,
          TierCurrent: 6,
          StatsTotal: { Kills: 218, DamagePlayer: 50414.27, HeadShots: 200, Groggies: 213, MostKillsInAGame: 13 },
        },
        Item_Weapon_Mk14_C: {
          XPTotal: 389556,
          LevelCurrent: 55,
          TierCurrent: 0,
          StatsTotal: { Kills: 31, DamagePlayer: 5646.57, HeadShots: 20, Groggies: 34, MostKillsInAGame: 6 },
        },
        Item_Weapon_Mk47Mutant_C: {
          XPTotal: 281905,
          LevelCurrent: 45,
          TierCurrent: 0,
          StatsTotal: { Kills: 33, DamagePlayer: 8446.77, HeadShots: 27, Groggies: 31, MostKillsInAGame: 2 },
        },
        Item_Weapon_Mosin_C: {
          XPTotal: 40355,
          LevelCurrent: 13,
          TierCurrent: 0,
          StatsTotal: { Kills: 5, DamagePlayer: 1087.79, HeadShots: 5, Groggies: 6, MostKillsInAGame: 3 },
        },
        Item_Weapon_NagantM1895_C: {
          XPTotal: 65171,
          LevelCurrent: 18,
          TierCurrent: 0,
          StatsTotal: { Kills: 11, DamagePlayer: 2055.69, HeadShots: 2, Groggies: 9, MostKillsInAGame: 3 },
        },
        Item_Weapon_P90_C: {
          XPTotal: 138582,
          LevelCurrent: 28,
          TierCurrent: 0,
          StatsTotal: { Kills: 3, DamagePlayer: 263.26, HeadShots: 1, Groggies: 2, MostKillsInAGame: 2 },
        },
        Item_Weapon_QBU88_C: {
          XPTotal: 139346,
          LevelCurrent: 28,
          TierCurrent: 0,
          StatsTotal: { Kills: 17, DamagePlayer: 3470.42, HeadShots: 18, Groggies: 18, MostKillsInAGame: 5 },
        },
        Item_Weapon_QBZ95_C: {
          XPTotal: 26253,
          LevelCurrent: 10,
          TierCurrent: 0,
          StatsTotal: { Kills: 4, DamagePlayer: 873.82, HeadShots: 2, Groggies: 5, MostKillsInAGame: 2 },
        },
        Item_Weapon_SCAR_L_C: {
          XPTotal: 371028,
          LevelCurrent: 54,
          TierCurrent: 0,
          StatsTotal: { Kills: 56, DamagePlayer: 8689.89, HeadShots: 34, Groggies: 44, MostKillsInAGame: 3 },
        },
        Item_Weapon_SKS_C: {
          XPTotal: 558469,
          LevelCurrent: 70,
          TierCurrent: 1,
          StatsTotal: { Kills: 129, DamagePlayer: 37080.27, HeadShots: 134, Groggies: 133, MostKillsInAGame: 9 },
        },
        Item_Weapon_Thompson_C: {
          XPTotal: 63631,
          LevelCurrent: 18,
          TierCurrent: 0,
          StatsTotal: { Kills: 15, DamagePlayer: 2266.32, HeadShots: 7, Groggies: 17, MostKillsInAGame: 3 },
        },
        Item_Weapon_UMP_C: {
          XPTotal: 276608,
          LevelCurrent: 44,
          TierCurrent: 0,
          StatsTotal: { Kills: 61, DamagePlayer: 8283.69, HeadShots: 31, Groggies: 44, MostKillsInAGame: 4 },
        },
        Item_Weapon_UZI_C: {
          XPTotal: 93081,
          LevelCurrent: 22,
          TierCurrent: 0,
          StatsTotal: { Kills: 13, DamagePlayer: 2486.43, HeadShots: 16, Groggies: 13, MostKillsInAGame: 2 },
        },
        Item_Weapon_VSS_C: {
          XPTotal: 183915,
          LevelCurrent: 34,
          TierCurrent: 0,
          StatsTotal: { Kills: 30, DamagePlayer: 4723.01, HeadShots: 11, Groggies: 18, MostKillsInAGame: 5 },
        },
        Item_Weapon_Vector_C: {
          XPTotal: 97572,
          LevelCurrent: 23,
          TierCurrent: 0,
          StatsTotal: { Kills: 23, DamagePlayer: 3187.42, HeadShots: 7, Groggies: 18, MostKillsInAGame: 3 },
        },
        Item_Weapon_Win1894_C: {
          XPTotal: 47278,
          LevelCurrent: 14,
          TierCurrent: 0,
          StatsTotal: { Kills: 7, DamagePlayer: 1375.77, HeadShots: 5, Groggies: 7, MostKillsInAGame: 3 },
        },
        Item_Weapon_Winchester_C: {
          XPTotal: 129009,
          LevelCurrent: 27,
          TierCurrent: 0,
          StatsTotal: { Kills: 20, DamagePlayer: 2243.75, HeadShots: 11, Groggies: 13, MostKillsInAGame: 3 },
        },
      },
    },
  },
};
