export const DUMMY_MASTERY_DATA = {
  data: {
    type: "weaponMasterySummary",
    id: "account.12ddde2e5fec4688ad5a3b10abfe8d59",
    attributes: {
      weaponSummaries: {
        Item_Weapon_ACE32_C: {
          XPTotal: 789219,
          LevelCurrent: 88,
          TierCurrent: 0,
          StatsTotal: { Kills: 43, DamagePlayer: 5048.55, HeadShots: 31, Groggies: 34, MostKillsInAGame: 4 },
        },
        Item_Weapon_AK47_C: {
          XPTotal: 433000,
          LevelCurrent: 60,
          TierCurrent: 0,
          StatsTotal: { Kills: 91, DamagePlayer: 13794.13, HeadShots: 43, Groggies: 65, MostKillsInAGame: 4 },
        },
        Item_Weapon_AUG_C: {
          XPTotal: 224445,
          LevelCurrent: 39,
          TierCurrent: 2,
          StatsTotal: { Kills: 24, DamagePlayer: 3251.99, HeadShots: 8, Groggies: 20, MostKillsInAGame: 5 },
        },
        Item_Weapon_AWM_C: {
          XPTotal: 22654,
          LevelCurrent: 10,
          TierCurrent: 0,
          StatsTotal: { Kills: 1, DamagePlayer: 510.51, HeadShots: 1, Groggies: 2, MostKillsInAGame: 1 },
        },
        Item_Weapon_Berreta686_C: {
          XPTotal: 40461,
          LevelCurrent: 13,
          TierCurrent: 0,
          StatsTotal: { Kills: 5, DamagePlayer: 764.04, HeadShots: 4, Groggies: 4, MostKillsInAGame: 1 },
        },
        Item_Weapon_BerylM762_C: {
          XPTotal: 286475,
          LevelCurrent: 45,
          TierCurrent: 3,
          StatsTotal: { Kills: 443, DamagePlayer: 67759.63, HeadShots: 328, Groggies: 371, MostKillsInAGame: 5 },
        },
        Item_Weapon_BizonPP19_C: {
          XPTotal: 50356,
          LevelCurrent: 15,
          TierCurrent: 0,
          StatsTotal: { Kills: 8, DamagePlayer: 1102.57, HeadShots: 4, Groggies: 8, MostKillsInAGame: 4 },
        },
        Item_Weapon_Crossbow_C: {
          XPTotal: 1555,
          LevelCurrent: 1,
          TierCurrent: 0,
          StatsTotal: { Kills: 0, DamagePlayer: 62.53, HeadShots: 0, Groggies: 0, MostKillsInAGame: 0 },
        },
        Item_Weapon_DP12_C: {
          XPTotal: 71258,
          LevelCurrent: 19,
          TierCurrent: 0,
          StatsTotal: { Kills: 23, DamagePlayer: 2436.94, HeadShots: 3, Groggies: 15, MostKillsInAGame: 5 },
        },
        Item_Weapon_DP28_C: {
          XPTotal: 30306,
          LevelCurrent: 11,
          TierCurrent: 0,
          StatsTotal: { Kills: 7, DamagePlayer: 945.13, HeadShots: 1, Groggies: 6, MostKillsInAGame: 1 },
        },
        Item_Weapon_Dragunov_C: {
          XPTotal: 626528,
          LevelCurrent: 76,
          TierCurrent: 1,
          StatsTotal: { Kills: 0, DamagePlayer: 0, HeadShots: 0, Groggies: 0, MostKillsInAGame: 0 },
        },
        Item_Weapon_FAMASG2_C: {
          XPTotal: 84083,
          LevelCurrent: 21,
          TierCurrent: 0,
          StatsTotal: { Kills: 0, DamagePlayer: 0, HeadShots: 0, Groggies: 0, MostKillsInAGame: 0 },
        },
        Item_Weapon_FNFal_C: {
          XPTotal: 178523,
          LevelCurrent: 33,
          TierCurrent: 3,
          StatsTotal: { Kills: 327, DamagePlayer: 89110.69, HeadShots: 307, Groggies: 343, MostKillsInAGame: 9 },
        },
        Item_Weapon_G18_C: {
          XPTotal: 26930,
          LevelCurrent: 10,
          TierCurrent: 0,
          StatsTotal: { Kills: 4, DamagePlayer: 482.45, HeadShots: 4, Groggies: 1, MostKillsInAGame: 2 },
        },
        Item_Weapon_G36C_C: {
          XPTotal: 51892,
          LevelCurrent: 15,
          TierCurrent: 0,
          StatsTotal: { Kills: 11, DamagePlayer: 1625.94, HeadShots: 7, Groggies: 13, MostKillsInAGame: 4 },
        },
        Item_Weapon_Groza_C: {
          XPTotal: 148738,
          LevelCurrent: 30,
          TierCurrent: 0,
          StatsTotal: { Kills: 17, DamagePlayer: 2401.14, HeadShots: 8, Groggies: 8, MostKillsInAGame: 3 },
        },
        Item_Weapon_HK416_C: {
          XPTotal: 588315,
          LevelCurrent: 73,
          TierCurrent: 2,
          StatsTotal: { Kills: 547, DamagePlayer: 80460.11, HeadShots: 418, Groggies: 508, MostKillsInAGame: 9 },
        },
        Item_Weapon_K2_C: {
          XPTotal: 92191,
          LevelCurrent: 22,
          TierCurrent: 0,
          StatsTotal: { Kills: 8, DamagePlayer: 1380.25, HeadShots: 2, Groggies: 7, MostKillsInAGame: 4 },
        },
        Item_Weapon_Kar98k_C: {
          XPTotal: 340667,
          LevelCurrent: 51,
          TierCurrent: 0,
          StatsTotal: { Kills: 4, DamagePlayer: 1907.80, HeadShots: 5, Groggies: 6, MostKillsInAGame: 1 },
        },
        Item_Weapon_M16A4_C: {
          XPTotal: 383938,
          LevelCurrent: 55,
          TierCurrent: 0,
          StatsTotal: { Kills: 51, DamagePlayer: 10160.56, HeadShots: 26, Groggies: 40, MostKillsInAGame: 3 },
        },
        Item_Weapon_M249_C: {
          XPTotal: 613935,
          LevelCurrent: 75,
          TierCurrent: 0,
          StatsTotal: { Kills: 17, DamagePlayer: 2688.82, HeadShots: 7, Groggies: 12, MostKillsInAGame: 4 },
        },
        Item_Weapon_M24_C: {
          XPTotal: 180982,
          LevelCurrent: 33,
          TierCurrent: 0,
          StatsTotal: { Kills: 10, DamagePlayer: 2166.92, HeadShots: 6, Groggies: 11, MostKillsInAGame: 2 },
        },
        Item_Weapon_MG3_C: {
          XPTotal: 49991,
          LevelCurrent: 15,
          TierCurrent: 0,
          StatsTotal: { Kills: 6, DamagePlayer: 693.75, HeadShots: 1, Groggies: 1, MostKillsInAGame: 2 },
        },
        Item_Weapon_MP5K_C: {
          XPTotal: 323640,
          LevelCurrent: 49,
          TierCurrent: 0,
          StatsTotal: { Kills: 13, DamagePlayer: 1999.59, HeadShots: 4, Groggies: 14, MostKillsInAGame: 5 },
        },
        Item_Weapon_Mini14_C: {
          XPTotal: 937483,
          LevelCurrent: 98,
          TierCurrent: 2,
          StatsTotal: { Kills: 366, DamagePlayer: 95350.14, HeadShots: 401, Groggies: 385, MostKillsInAGame: 7 },
        },
        Item_Weapon_Mk12_C: {
          XPTotal: 952500,
          LevelCurrent: 99,
          TierCurrent: 6,
          StatsTotal: { Kills: 218, DamagePlayer: 50414.27, HeadShots: 200, Groggies: 213, MostKillsInAGame: 13 },
        },
        Item_Weapon_Mk14_C: {
          XPTotal: 389556,
          LevelCurrent: 55,
          TierCurrent: 0,
          StatsTotal: { Kills: 31, DamagePlayer: 5646.57, HeadShots: 20, Groggies: 34, MostKillsInAGame: 6 },
        },
        Item_Weapon_Mk47Mutant_C: {
          XPTotal: 281905,
          LevelCurrent: 45,
          TierCurrent: 0,
          StatsTotal: { Kills: 33, DamagePlayer: 8446.77, HeadShots: 27, Groggies: 31, MostKillsInAGame: 2 },
        },
        Item_Weapon_Mosin_C: {
          XPTotal: 40355,
          LevelCurrent: 13,
          TierCurrent: 0,
          StatsTotal: { Kills: 5, DamagePlayer: 1087.79, HeadShots: 5, Groggies: 6, MostKillsInAGame: 3 },
        },
        Item_Weapon_NagantM1895_C: {
          XPTotal: 65171,
          LevelCurrent: 18,
          TierCurrent: 0,
          StatsTotal: { Kills: 11, DamagePlayer: 2055.69, HeadShots: 2, Groggies: 9, MostKillsInAGame: 3 },
        },
        Item_Weapon_P90_C: {
          XPTotal: 138582,
          LevelCurrent: 28,
          TierCurrent: 0,
          StatsTotal: { Kills: 3, DamagePlayer: 263.26, HeadShots: 1, Groggies: 2, MostKillsInAGame: 2 },
        },
        Item_Weapon_QBU88_C: {
          XPTotal: 139346,
          LevelCurrent: 28,
          TierCurrent: 0,
          StatsTotal: { Kills: 17, DamagePlayer: 3470.42, HeadShots: 18, Groggies: 18, MostKillsInAGame: 5 },
        },
        Item_Weapon_QBZ95_C: {
          XPTotal: 26253,
          LevelCurrent: 10,
          TierCurrent: 0,
          StatsTotal: { Kills: 4, DamagePlayer: 873.82, HeadShots: 2, Groggies: 5, MostKillsInAGame: 2 },
        },
        Item_Weapon_SCAR_L_C: {
          XPTotal: 371028,
          LevelCurrent: 54,
          TierCurrent: 0,
          StatsTotal: { Kills: 56, DamagePlayer: 8689.89, HeadShots: 34, Groggies: 44, MostKillsInAGame: 3 },
        },
        Item_Weapon_SKS_C: {
          XPTotal: 558469,
          LevelCurrent: 70,
          TierCurrent: 1,
          StatsTotal: { Kills: 129, DamagePlayer: 37080.27, HeadShots: 134, Groggies: 133, MostKillsInAGame: 9 },
        },
        Item_Weapon_Thompson_C: {
          XPTotal: 63631,
          LevelCurrent: 18,
          TierCurrent: 0,
          StatsTotal: { Kills: 15, DamagePlayer: 2266.32, HeadShots: 7, Groggies: 17, MostKillsInAGame: 3 },
        },
        Item_Weapon_UMP_C: {
          XPTotal: 276608,
          LevelCurrent: 44,
          TierCurrent: 0,
          StatsTotal: { Kills: 61, DamagePlayer: 8283.69, HeadShots: 31, Groggies: 44, MostKillsInAGame: 4 },
        },
        Item_Weapon_UZI_C: {
          XPTotal: 93081,
          LevelCurrent: 22,
          TierCurrent: 0,
          StatsTotal: { Kills: 13, DamagePlayer: 2486.43, HeadShots: 16, Groggies: 13, MostKillsInAGame: 2 },
        },
        Item_Weapon_VSS_C: {
          XPTotal: 183915,
          LevelCurrent: 34,
          TierCurrent: 0,
          StatsTotal: { Kills: 30, DamagePlayer: 4723.01, HeadShots: 11, Groggies: 18, MostKillsInAGame: 5 },
        },
        Item_Weapon_Vector_C: {
          XPTotal: 97572,
          LevelCurrent: 23,
          TierCurrent: 0,
          StatsTotal: { Kills: 23, DamagePlayer: 3187.42, HeadShots: 7, Groggies: 18, MostKillsInAGame: 3 },
        },
        Item_Weapon_Win1894_C: {
          XPTotal: 47278,
          LevelCurrent: 14,
          TierCurrent: 0,
          StatsTotal: { Kills: 7, DamagePlayer: 1375.77, HeadShots: 5, Groggies: 7, MostKillsInAGame: 3 },
        },
        Item_Weapon_Winchester_C: {
          XPTotal: 129009,
          LevelCurrent: 27,
          TierCurrent: 0,
          StatsTotal: { Kills: 20, DamagePlayer: 2243.75, HeadShots: 11, Groggies: 13, MostKillsInAGame: 3 },
        },
      },
    },
  },
};

export type WeaponSummary = {
  XPTotal: number;
  LevelCurrent: number;
  TierCurrent: number;
  StatsTotal: {
    Kills: number;
    DamagePlayer: number;
    HeadShots: number;
    Groggies: number;
    MostKillsInAGame: number;
  };
};

export const WEAPON_NAMES: Record<string, string> = {
  Item_Weapon_ACE32_C: "ACE32",
  Item_Weapon_AK47_C: "AKM",
  Item_Weapon_AUG_C: "AUG A3",
  Item_Weapon_AWM_C: "AWM",
  Item_Weapon_Berreta686_C: "S686",
  Item_Weapon_BerylM762_C: "Beryl M762",
  Item_Weapon_BizonPP19_C: "PP-19 Bizon",
  Item_Weapon_Crossbow_C: "Crossbow",
  Item_Weapon_DP12_C: "DBS",
  Item_Weapon_DP28_C: "DP-28",
  Item_Weapon_Dragunov_C: "Dragunov",
  Item_Weapon_FAMASG2_C: "FAMAS",
  Item_Weapon_FNFal_C: "SLR",
  Item_Weapon_G18_C: "P18C",
  Item_Weapon_G36C_C: "G36C",
  Item_Weapon_Groza_C: "Groza",
  Item_Weapon_HK416_C: "M416",
  Item_Weapon_K2_C: "K2",
  Item_Weapon_Kar98k_C: "Kar98k",
  Item_Weapon_M16A4_C: "M16A4",
  Item_Weapon_M1911_C: "P1911",
  Item_Weapon_M249_C: "M249",
  Item_Weapon_M24_C: "M24",
  Item_Weapon_M9_C: "P92",
  Item_Weapon_MG3_C: "MG3",
  Item_Weapon_MP5K_C: "MP5K",
  Item_Weapon_MP9_C: "MP9",
  Item_Weapon_Mini14_C: "Mini14",
  Item_Weapon_Mk12_C: "Mk12",
  Item_Weapon_Mk14_C: "Mk14",
  Item_Weapon_Mk47Mutant_C: "Mk47 Mutant",
  Item_Weapon_Mosin_C: "Mosin-Nagant",
  Item_Weapon_NagantM1895_C: "R1895",
  Item_Weapon_P90_C: "P90",
  Item_Weapon_QBU88_C: "QBU",
  Item_Weapon_QBZ95_C: "QBZ95",
  Item_Weapon_SCAR_L_C: "SCAR-L",
  "Item_Weapon_SCAR-L_C": "SCAR-L",
  Item_Weapon_SKS_C: "SKS",
  Item_Weapon_Thompson_C: "Tommy Gun",
  Item_Weapon_UMP_C: "UMP45",
  Item_Weapon_UZI_C: "Micro UZI",
  Item_Weapon_VSS_C: "VSS",
  Item_Weapon_Vector_C: "Vector",
  Item_Weapon_Win1894_C: "Win94",
  Item_Weapon_Winchester_C: "S1897",
  Item_Weapon_vz61Skorpion_C: "Skorpion",
  Item_Weapon_JS9_C: "JS9",
  Item_Weapon_L6_C: "Lynx AMR",
  Item_Weapon_OriginS12_C: "O12",
  Item_Weapon_Saiga12_C: "S12K",
  Item_Weapon_Sawnoff_C: "Sawed-off",
  Item_Weapon_DesertEagle_C: "Deagle",
  Item_Weapon_Rhino_C: "Rhino",
  Item_Weapon_PanzerFaust100M_C: "Panzerfaust",
  Item_Weapon_Mortar_C: "Mortar",
  Item_Weapon_Molotov_C: "Molotov",
  Item_Weapon_Grenade_C: "Grenade",
  Item_Weapon_BluezoneGrenade_C: "Bluezone Grenade",
};

// 무기 카테고리
export const WEAPON_CATEGORIES: Record<string, string[]> = {
  AR: [
    "Item_Weapon_ACE32_C",
    "Item_Weapon_AK47_C",
    "Item_Weapon_AUG_C",
    "Item_Weapon_BerylM762_C",
    "Item_Weapon_FAMASG2_C",
    "Item_Weapon_G36C_C",
    "Item_Weapon_Groza_C",
    "Item_Weapon_HK416_C",
    "Item_Weapon_K2_C",
    "Item_Weapon_M16A4_C",
    "Item_Weapon_QBZ95_C",
    "Item_Weapon_SCAR_L_C",
    "Item_Weapon_SCAR-L_C",
  ],
  DMR: [
    "Item_Weapon_Dragunov_C",
    "Item_Weapon_FNFal_C",
    "Item_Weapon_Mk14_C",
    "Item_Weapon_Mk47Mutant_C",
    "Item_Weapon_Mini14_C",
    "Item_Weapon_Mk12_C",
    "Item_Weapon_QBU88_C",
    "Item_Weapon_SKS_C",
    "Item_Weapon_VSS_C",
  ],
  SR: [
    "Item_Weapon_AWM_C",
    "Item_Weapon_Kar98k_C",
    "Item_Weapon_M24_C",
    "Item_Weapon_Mosin_C",
    "Item_Weapon_Win1894_C",
    "Item_Weapon_L6_C",
  ],
  SMG: [
    "Item_Weapon_BizonPP19_C",
    "Item_Weapon_MP5K_C",
    "Item_Weapon_MP9_C",
    "Item_Weapon_P90_C",
    "Item_Weapon_Thompson_C",
    "Item_Weapon_UMP_C",
    "Item_Weapon_UZI_C",
    "Item_Weapon_Vector_C",
    "Item_Weapon_vz61Skorpion_C",
    "Item_Weapon_JS9_C",
  ],
  LMG: [
    "Item_Weapon_DP28_C",
    "Item_Weapon_M249_C",
    "Item_Weapon_MG3_C",
  ],
  SG: [
    "Item_Weapon_Berreta686_C",
    "Item_Weapon_DP12_C",
    "Item_Weapon_OriginS12_C",
    "Item_Weapon_Saiga12_C",
    "Item_Weapon_Sawnoff_C",
    "Item_Weapon_Winchester_C",
  ],
  PISTOL: [
    "Item_Weapon_G18_C",
    "Item_Weapon_M1911_C",
    "Item_Weapon_M9_C",
    "Item_Weapon_NagantM1895_C",
    "Item_Weapon_DesertEagle_C",
    "Item_Weapon_Rhino_C",
  ],
  SPECIAL: [
    "Item_Weapon_Crossbow_C",
    "Item_Weapon_Grenade_C",
    "Item_Weapon_Molotov_C",
    "Item_Weapon_BluezoneGrenade_C",
    "Item_Weapon_Mortar_C",
    "Item_Weapon_PanzerFaust100M_C",
  ],
};

export const TIER_INFO: Record<number, { label: string; color: string; bg: string; border: string }> = {
  0: { label: "없음", color: "text-gray-500", bg: "bg-gray-100 dark:bg-gray-700", border: "border-gray-300 dark:border-gray-600" },
  1: { label: "브론즈", color: "text-amber-700", bg: "bg-amber-50 dark:bg-amber-900/20", border: "border-amber-400" },
  2: { label: "실버", color: "text-slate-500", bg: "bg-slate-50 dark:bg-slate-800/50", border: "border-slate-400" },
  3: { label: "골드", color: "text-yellow-500", bg: "bg-yellow-50 dark:bg-yellow-900/20", border: "border-yellow-400" },
  4: { label: "플래티넘", color: "text-cyan-500", bg: "bg-cyan-50 dark:bg-cyan-900/20", border: "border-cyan-400" },
  5: { label: "다이아", color: "text-blue-500", bg: "bg-blue-50 dark:bg-blue-900/20", border: "border-blue-500" },
  6: { label: "마스터", color: "text-purple-500", bg: "bg-purple-50 dark:bg-purple-900/20", border: "border-purple-500" },
};
